# Generated by Grok from demo files provided by the LightRAG repo. Has not been tested yet.

import asyncio
import nest_asyncio
import os
import inspect
import logging
from lightrag import LightRAG, QueryParam
from lightrag.llm.ollama import ollama_model_complete, ollama_embed
from lightrag.utils import EmbeddingFunc
from lightrag.kg.shared_storage import initialize_pipeline_status
import time


nest_asyncio.apply()


class LightRAG_Interface:
    def __init__(self, working_dir, llm_model_func, llm_model_name, **kwargs):
        self.working_dir = working_dir
        self.llm_model_func = llm_model_func
        self.llm_model_name = llm_model_name
        self.kwargs = kwargs
        self.rag = None

    async def initialize(self):
        raise NotImplementedError("This method should be implemented by subclasses")

    async def query(self, query, param):
        raise NotImplementedError("This method should be implemented by subclasses")

    def insert(self, text):
        raise NotImplementedError("This method should be implemented by subclasses")

    async def print_stream(self, stream):
        async for chunk in stream:
            print(chunk, end="", flush=True)

    @staticmethod
    def create_working_directory(working_dir):
        if not os.path.exists(working_dir):
            os.mkdir(working_dir)


class LightRAG_Local(LightRAG_Interface):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.llm_model_max_async = kwargs.get('llm_model_max_async', 4)
        self.llm_model_max_token_size = kwargs.get('llm_model_max_token_size', 32768)
        self.embedding_func = kwargs.get('embedding_func', EmbeddingFunc(
            embedding_dim=768,
            max_token_size=8192,
            func=lambda texts: ollama_embed(texts, embed_model="nomic-embed-text", host="http://localhost:11434")
        ))

    async def initialize(self):
        self.create_working_directory(self.working_dir)
        self.rag = LightRAG(
            working_dir=self.working_dir,
            llm_model_func=self.llm_model_func,
            llm_model_name=self.llm_model_name,
            llm_model_max_async=self.llm_model_max_async,
            llm_model_max_token_size=self.llm_model_max_token_size,
            llm_model_kwargs={
                "host": "http://localhost:11434",
                "options": {"num_ctx": self.llm_model_max_token_size},
            },
            embedding_func=self.embedding_func,
        )
        await self.rag.initialize_storages()
        await initialize_pipeline_status()

    async def query(self, query, param):
        if self.rag:
            return self.rag.query(query, param)
        else:
            raise Exception("LightRAG instance not initialized")

    def insert(self, text):
        if self.rag:
            self.rag.insert(text)
        else:
            raise Exception("LightRAG instance not initialized")


def main():
    WORKING_DIR = "./dickens_ollama"
    logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.INFO)

    # Initialize LightRAGLocal instance
    rag_local = LightRAGLocal(
        working_dir=WORKING_DIR,
        llm_model_func=ollama_model_complete,
        llm_model_name="qwen2:latest"
    )

    # Initialize RAG instance
    asyncio.run(rag_local.initialize())

    # Insert example text
    with open("./book.txt", "r", encoding="utf-8") as f:
        rag_local.insert(f.read())
        
    query = "What is the main point of the story?"

    # Start timing
    start_time = time.time()
    
    print("\nHybrid Search:")
    result = asyncio.run(rag_local.query(query, QueryParam(mode="hybrid")))
    print(result)
    
    # End timing
    end_time = time.time()

    # Calculate and print the time taken
    print(f"Operation took {end_time - start_time} seconds")

if __name__ == "__main__":
    main()