# Generated by Grok from demo files provided by the LightRAG repo. Has not been tested yet.

import asyncio
import nest_asyncio
import os
import time
import inspect
import logging
import logging.config
from lightrag import LightRAG, QueryParam
from lightrag.llm.openai import gpt_4o_mini_complete, openai_embed
from lightrag.llm.ollama import ollama_model_complete, ollama_embed
from lightrag.utils import EmbeddingFunc
from lightrag.kg.shared_storage import initialize_pipeline_status
from lightrag.utils import logger, set_verbose_debug



nest_asyncio.apply()


class LightRAG_Interface:
    def __init__(self, working_dir, llm_model_func, llm_model_name, **kwargs):
        self.working_dir = working_dir
        self.llm_model_func = llm_model_func
        self.llm_model_name = llm_model_name
        self.kwargs = kwargs
        self.rag = None

    async def initialize(self):
        raise NotImplementedError("This method should be implemented by subclasses")

    async def query(self, query, param):
        raise NotImplementedError("This method should be implemented by subclasses")

    def insert(self, text):
        raise NotImplementedError("This method should be implemented by subclasses")

    async def print_stream(self, stream):
        async for chunk in stream:
            print(chunk, end="", flush=True)

    @staticmethod
    def create_working_directory(working_dir):
        if not os.path.exists(working_dir):
            os.mkdir(working_dir)
            
            
class LightRAG_OpenAI(LightRAG_Interface):
    def __init__(self, working_dir, **kwargs):
        super().__init__(working_dir=working_dir, llm_model_func=gpt_4o_mini_complete, llm_model_name="gpt-4o-mini", **kwargs)
        self.embedding_func = kwargs.get('embedding_func', openai_embed)
        self.llm_model_max_token_size = kwargs.get('llm_model_max_token_size', 4096)  # Default token size for gpt-4o-mini
        self.configure_logging()

    def configure_logging(self):
        """Configure logging for the application"""
        # Reset any existing handlers to ensure clean configuration
        for logger_name in ["uvicorn", "uvicorn.access", "uvicorn.error", "lightrag"]:
            logger_instance = logging.getLogger(logger_name)
            logger_instance.handlers = []
            logger_instance.filters = []

        # Get log directory path from environment variable or use current directory
        log_dir = os.getenv("LOG_DIR", os.getcwd())
        log_file_path = os.path.abspath(os.path.join(log_dir, "lightrag_openai.log"))

        os.makedirs(os.path.dirname(log_dir), exist_ok=True)

        # Get log file max size and backup count from environment variables
        log_max_bytes = int(os.getenv("LOG_MAX_BYTES", 10485760))  # Default 10MB
        log_backup_count = int(os.getenv("LOG_BACKUP_COUNT", 5))  # Default 5 backups

        logging.config.dictConfig(
            {
                "version": 1,
                "disable_existing_loggers": False,
                "formatters": {
                    "default": {
                        "format": "%(levelname)s: %(message)s",
                    },
                    "detailed": {
                        "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
                    },
                },
                "handlers": {
                    "console": {
                        "formatter": "default",
                        "class": "logging.StreamHandler",
                        "stream": "ext://sys.stderr",
                    },
                    "file": {
                        "formatter": "detailed",
                        "class": "logging.handlers.RotatingFileHandler",
                        "filename": log_file_path,
                        "maxBytes": log_max_bytes,
                        "backupCount": log_backup_count,
                        "encoding": "utf-8",
                    },
                },
                "loggers": {
                    "lightrag": {
                        "handlers": ["console", "file"],
                        "level": "INFO",
                        "propagate": False,
                    },
                },
            }
        )

        # Set the logger level to INFO
        logger.setLevel(logging.INFO)
        # Enable verbose debug if needed
        set_verbose_debug(os.getenv("VERBOSE_DEBUG", "false").lower() == "true")

    async def initialize(self):
        self.create_working_directory(self.working_dir)
        self.rag = LightRAG(
            working_dir=self.working_dir,
            embedding_func=self.embedding_func,
            llm_model_func=self.llm_model_func,
            llm_model_max_token_size=self.llm_model_max_token_size,
        )
        await self.rag.initialize_storages()
        await initialize_pipeline_status()

    async def query(self, query, param, stream=False):
        if self.rag:
            result = await self.rag.aquery(query, param)
            if stream and inspect.isasyncgen(result):
                await self.print_stream(result)
            return result
        else:
            raise Exception("LightRAG instance not initialized")

    async def insert(self, text):
        if self.rag:
            await self.rag.ainsert(text)
        else:
            raise Exception("LightRAG instance not initialized")

    async def print_stream(self, stream):
        async for chunk in stream:
            print(chunk, end="", flush=True)


class LightRAG_Local(LightRAG_Interface):
    def __init__(self, working_dir, **kwargs):
        super().__init__(working_dir=working_dir, llm_model_func=ollama_model_complete, llm_model_name="qwen3:latest", **kwargs)
        self.llm_model_max_async = kwargs.get('llm_model_max_async', 4)
        self.llm_model_max_token_size = kwargs.get('llm_model_max_token_size', 32768)
        
    def initialize(self):
        self.rag = asyncio.run(self.initialize_rag())
                
    async def initialize_rag(self):
        rag = LightRAG(
            working_dir=self.working_dir,
            llm_model_func=self.llm_model_func,
            llm_model_name=self.llm_model_name,
            llm_model_max_async=self.llm_model_max_async,
            llm_model_max_token_size=self.llm_model_max_token_size,
            llm_model_kwargs={
                "host": "http://localhost:11434",
                "options": {"num_ctx": self.llm_model_max_token_size},
            },
            embedding_func=EmbeddingFunc(
                embedding_dim=768,
                max_token_size=8192,
                func=lambda texts: ollama_embed(
                    texts, embed_model="nomic-embed-text", host="http://localhost:11434"
                ),
            ),
        )

        await rag.initialize_storages()
        await initialize_pipeline_status()
        
        return rag

    def query(self, user_prompt, param, chat_summary='No Chat Summary Available'):        
        light_rag_query = '''\
        ... You are an AI assistant with access to a vast knowledge base of information stored in a text file related to the chat history.
        ... Your goal is to provide the most accurate and comprehensive response to the user's query by utilizing all relevant information from the file.
        ...
        ... Please adhere to the following guidelines when processing the user's query:
        ... 1. **Maximize Information Retrieval:** Use all available data from the text file to answer the user's query. This includes:
        ...    - Relevant conversation history between the user and the AI assistant.
        ...    - Any documents or information indexed in the file that pertains to the user's request.
        ... 2. **Contextual Understanding:** Ensure that your response provides enough context for any Large Language Model to understand the conversation's background, trajectory, and key topics.
        ... 3. **Comprehensive Summary:** When summarizing, cover:
        ...    - Key points from the conversation.
        ...    - Relevant snippets or summaries from any documents or data indexed in the file.
        ... 4. **Accuracy and Factual Grounding:** Base your answers on the information available in the file to ensure factual accuracy.
        ... 5. **Third-Person Perspective:** Maintain a third-person perspective when discussing the conversation or summarizing information.
        ... 6. **Refer to the AI Assistant:** If there are references to responses from the AI in the chat history, refer to that AI as 'the AI'.
        ...
        ... For your reference, below is the summary of the entire chat history (if available). 
        ... ----------------------
        ... {chat_summary}
        ... ----------------------
        ...
        ... Please respond to the following user query with the most comprehensive and accurate information you can provide from the text file: 
        ... ----------------------
        ... {user_query}
        ... ----------------------\
        ... '''.format(chat_summary=chat_summary, user_query=user_prompt)
                
        self.rag = asyncio.run(self.initialize_rag())
        if self.rag:
            return self.rag.query(light_rag_query, param)
        else:
            raise Exception("LightRAG instance not initialized")

    def insert(self, text):
        if self.rag:
            self.rag.insert(text)
        else:
            raise Exception("LightRAG instance not initialized")